name: Go

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install Deps
        run: make dep

      - name: Test
        run: make test

  race_detection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install Deps
        run: make dep

      - name: Race detection
        run: make race

  memory_sanitization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install Clang
        run: |
          sudo apt update
          sudo apt install clang-11
      - name: Install Deps
        run: make dep

      - name: Memory sanitization
        run: make msan

  lint-go-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install Deps
        run: make dep

      - name: Install revive
        run: go install github.com/mgechev/revive@v1.3.4

      - name: Lint
        run: revive -config ./go-sdk/revive.toml -formatter stylish ./go-sdk/...

  lint-lwee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install Deps
        run: make dep

      - name: Install revive
        run: go install github.com/mgechev/revive@v1.3.4

      - name: Lint
        run: revive -config ./lwee/revive.toml -formatter stylish --exclude ./lwee/e2e/... ./lwee/...

  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Install Deps
        run: make dep

      - name: Create Code Coverage
        run: make coverhtml

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: OS
          fail_ci_if_error: true
          files: ./lwee/coverage.txt
          flags: unittests
          verbose: true
